# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 552958fc16011b9da5490bbacb029ee8d4bf8f98a908538ad6d606eac6a00f8dfa4bb26bd9de556c14ec80dffa9b454abded34933873cb6bec93f796e8dfda23

test:
  secret_key_base: 8e3700b3ec93eec228098382e4f7208a32652dd4ae658c48b169d496f6068e24ca3918a9f363ea012b43e63e0635408ca45dbf759fbcf2a1d381d06d6ced92af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
